<a href="https://colab.research.google.com/github/Luciahelenasantos/POS_GRADUACAO_PUC/blob/main/Machine_Learning/separa_teste_e_treino.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
# Imports necessários
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split # para particionar em bases de treino e teste (holdout)
from sklearn.model_selection import StratifiedKFold # biblioteca para a separação de treino e teste

In [19]:
# Função que cria a variável ordinal para a qualdade do ar

def calcula_classe_qualiar(qualidade):
  vqualidade = qualidade

  if qualidade == "Good":
    return 1
  elif qualidade == "Moderate":
    return 2
  elif qualidade == "Unhealthy":
    return 3
  elif qualidade == "Unhealthy for Sensitive Groups":
    return 4
  elif qualidade == "Very Unhealthy":
    return 5
  else:
    return 6

In [3]:
# Importando o arquivo em formato csv hospedado em My Drive

dados_vazios = [ " " ]

QualidadeAR = pd.read_csv("https://raw.githubusercontent.com/Luciahelenasantos/POS_GRADUACAO_PUC/main/Machine_Learning/global_air_pollution_dataset.csv", na_values = dados_vazios)

In [4]:
QualidadeAR.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23463 entries, 0 to 23462
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Country             23036 non-null  object
 1   City                23462 non-null  object
 2   AQI Value           23463 non-null  int64 
 3   AQI Category        23463 non-null  object
 4   CO AQI Value        23463 non-null  int64 
 5   CO AQI Category     23463 non-null  object
 6   Ozone AQI Value     23463 non-null  int64 
 7   Ozone AQI Category  23463 non-null  object
 8   NO2 AQI Value       23463 non-null  int64 
 9   NO2 AQI Category    23463 non-null  object
 10  PM2.5 AQI Value     23463 non-null  int64 
 11  PM2.5 AQI Category  23463 non-null  object
dtypes: int64(5), object(7)
memory usage: 2.1+ MB


In [10]:
QualidadeAR2Previsores  = QualidadeAR[['CO AQI Value', 'Ozone AQI Value', 'PM2.5 AQI Value',
                                        'NO2 AQI Value', 'AQI Value']]

In [11]:
QualidadeAR2Previsores

CO AQI Value  Ozone AQI Value  PM2.5 AQI Value  NO2 AQI Value  \
0                 1               36               51              0   
1                 1                5               41              1   
2                 1               39               66              2   
3                 1               34               20              0   
4                 0               22                6              0   
...             ...              ...              ...            ...   
23458             3              154              184              2   
23459             1               20               50              5   
23460             1               22               50              1   
23461             1               44               71              2   
23462             1               38               70              0   

       AQI Value  
0             51  
1             41  
2             66  
3             34  
4             22  
...          ...  
23458        184  
23459         50  
23460         50  
23461         71  
23462         70  

[23463 rows x 5 columns]

In [49]:
test_size = 0.20 # tamanho do conjunto de teste
seed = 7 # semente aleatória

# Separação em conjuntos de treino e teste
array = QualidadeAR2Previsores.values
X = array[:,0:4]
y = array[:,4]
X_train, X_test, y_train, y_test = train_test_split(X, y,
    test_size=test_size, shuffle=True, random_state=seed, stratify=y) # holdout com estratificação

# Parâmetros e partições da validação cruzada
scoring = 'accuracy'
num_particoes = 10
kfold = StratifiedKFold(n_splits=num_particoes, shuffle=True, random_state=seed) # validação cruzada com estratificação

ValueError: ignored

In [50]:
X

array([[ 1, 36, 51,  0],
       [ 1,  5, 41,  1],
       [ 1, 39, 66,  2],
       ...,
       [ 1, 22, 50,  1],
       [ 1, 44, 71,  2],
       [ 1, 38, 70,  0]])

In [51]:
y

array([51, 41, 66, ..., 50, 71, 70])

In [52]:
kfold

StratifiedKFold(n_splits=10, random_state=7, shuffle=True)

usando o dado codificado


In [21]:
# Criamos uma cópia do banco original QualidadeAR2

QualidadeAR2 = pd.DataFrame.copy(QualidadeAR)

In [22]:
# Criando a variável numérica que identifica a classificação do AQI para cada poluente

QualidadeAR2['AQI_Category_Num'] = QualidadeAR2['AQI Category'].apply(calcula_classe_qualiar)
QualidadeAR2['CO_AQI_Category_Num'] = QualidadeAR2['CO AQI Category'].apply(calcula_classe_qualiar)
QualidadeAR2['Ozone_AQI_Category_Num'] = QualidadeAR2['Ozone AQI Category'].apply(calcula_classe_qualiar)
QualidadeAR2['NO2_AQI_Category_Num'] = QualidadeAR2['NO2 AQI Category'].apply(calcula_classe_qualiar)
QualidadeAR2['PM2.5_AQI_Category_Num'] = QualidadeAR2['PM2.5 AQI Category'].apply(calcula_classe_qualiar)

In [36]:
QualidadeAR3Previsores  = QualidadeAR2[['CO_AQI_Category_Num', 'Ozone_AQI_Category_Num', 'NO2_AQI_Category_Num',
                                       'PM2.5_AQI_Category_Num', 'AQI_Category_Num']]

In [53]:
QualidadeAR3Previsores

CO_AQI_Category_Num  Ozone_AQI_Category_Num  NO2_AQI_Category_Num  \
0                        1                       1                     1   
1                        1                       1                     1   
2                        1                       1                     1   
3                        1                       1                     1   
4                        1                       1                     1   
...                    ...                     ...                   ...   
23458                    1                       3                     1   
23459                    1                       1                     1   
23460                    1                       1                     1   
23461                    1                       1                     1   
23462                    1                       1                     1   

       PM2.5_AQI_Category_Num  AQI_Category_Num  
0                           2                 2  
1                           1                 1  
2                           2                 2  
3                           1                 1  
4                           1                 1  
...                       ...               ...  
23458                       3                 3  
23459                       1                 1  
23460                       1                 1  
23461                       2                 2  
23462                       2                 2  

[23463 rows x 5 columns]

In [46]:
test_size = 0.20 # tamanho do conjunto de teste
seed = 7 # semente aleatória

# Separação em conjuntos de treino e teste
array = QualidadeAR3Previsores.values
X3 = array[:,0:4]
y3 = array[:,4]
X3_train, X3_test, y3_train, y3_test = train_test_split(X3, y3,
    test_size=test_size, shuffle=True, random_state=seed, stratify=y3) # holdout com estratificação

# Parâmetros e partições da validação cruzada
scoring = 'accuracy'
num_particoes = 10
kfold3 = StratifiedKFold(n_splits=num_particoes, shuffle=True, random_state=seed) # validação cruzada com estratificação

In [44]:
X3

array([[1, 1, 1, 2],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       ...,
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2]])

In [45]:
y3

array([2, 1, 2, ..., 1, 2, 2])

In [47]:
kfold3

StratifiedKFold(n_splits=10, random_state=7, shuffle=True)